apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgAoXr1pvDMlVT34UKONnQPkKOfxRmknaWpsnFRzRIXVv26h7baLVBaHhJoh2wpL7A0EZiDF5rqoay+2fLfAw8D/0O/CZ+vjP8OCiURDLm8i6jzufi8f+lonhIr8c+wBHC39U+8Fna4v14X8Llp3HIuidqE2fBx93rURxZLj40s++4wQbzqa5hUbCviaFyVRMt0SSfLND00t5ZyVTYkWnufq1D/DVjeR90Q1mXTonJ/cov2VyW1G8hqznYpKgNT63yAICu06enBHz9QOsyntS+s0e66ublPT67t5+nex27RJKLx8Vm2JAaIZs4Q7OfXQ0i0QYnwM5Jp4VENz8MJTr5S4R4eky5px7SrE00FUiCmD1SRsAyXGNK2c+aCIO0n6bMD7au/peGmT09jEl6SZIYy97MPxefpTfHhY0zeFuLBCsM9bPrrSC8BpD/aNcFxTib9+9epZDi3m1JkSdsm7F42yCPwxwCX6CGXQM92zNnWdetRhA3j+BSJbFebljguQoz18iOkZUWYQEIt5E1r3HXcYZJ38hnScBB6w2lsfwG74RTclPNCqqJkveF1EZcNi0p2mo7DJc8cubp/jguLkgci0yZ5GLqlbxbt2LSV6RLCsipkmJBI10B4MpSK5lvmezbAjdRdG9GYFoT6JhgQp7wk8OjuDxYOaDHDqlEg3Szu+ND9a7MwRULUdA3Qir0yZZxKBUDjNKQbpD/i7LeXXvC/wNdmroP3cr+T4kEk612tfUxiIY5GanF/OKKvS5TR7q8+Fq8Mgj4p1bBnsKtViQHN9vQZebbIdMmzAtmYyrZLecXtBJF0YMZpXGzmn440=
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

