apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgDHJwy03Zx2Vd54JVvFAXOjLYHdxpi1EXNY47Wavjma0bzQsy4q+so4K33mINYD5OY+qoCawG686W7iPBjgQxluZFfa8229OXNkqYvM1douRkQsS8KMVkRtJPRYsCr/SBXVFJRqhIDW5iwvhiPSR9jDT2R72HVW2vjBW6wYKb6av/CAiZIenNUlLYLN60ZF5yziJPgk1R/UkA9uXI50LbajJU+nDLyN7VUB/X4OwoFFpy9dGIMbzeLh3qeFpwynJvn+I7EQyq8Cd9HK9BXq2DvcMs72R+gzCvEWC/mRsddrfM5/fxShfgt8DHjWd9bi4RLYnTesVwtT6ibyS+4wKv2ilW+Bs32GLo76kqIHmqJG0Q9n8F8VMLLjrnrfpSflmYPSUueATVi32S+1vwW71Rj0ZL11uKCHxV7QnSTttRRB+vuzi76rZQK7fYkLvqbRdPu5J3XG67X3ceSBGgCKHyDoRiVQ1feoODl1i7g2x7iB0MHgEZSVAsF7C0zrLWAdxNOFkVR5yu7YT4p2F35DDvGIrUfB3eQ6acHTJZQemtJxo9I7pEcpxPyGWtFrcpJBdidCNZiniTnP/2bFQykVCwxo5v9D6Zgx/R38sjH8eY/0/TbdO2wz0FuXcjt6viu1Ij4lgXHs0fRTQ/35IuucUtQ41dz1CfbrMS1dRjCbUQig4DJwMUTdNqctNvFHCaw95+/2ZT+hNVa/f2IEoD+CMrW2oo8vnipOhThD+Jbx7A4HEqWYeLp2LMJaPyQn7Ae/J7XfahgW/XejASHDlmTRQdFgRCkwJtUUojiYIu81cqzLUIvJCx3SsFJFPI6NK0U=
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

